server:
  port: 8080
  address: 192.168.0.19
spring:
  application:
    name: gateway
eureka:
  client:
    service-url:
      defaultZone:
        http://localhost:9000/eureka
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
    ip-address: 192.168.0.19