server:
  port: 9300
  address: 127.0.0.1
spring:
  application:
    name: project
eureka:
  client:
    service-url:
      defaultZone:
        http://localhost:9000/eureka
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true